package AutoGeneratedPOJOs.CreateBook;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.mapper.ObjectMapperType;
import org.testng.annotations.Test;

public class CreateBook {

    @Test
    public void createBookWithValidParams(){

        Bookingdates bookingdates = new Bookingdates();
        bookingdates.setCheckin("2018-01-01");
        bookingdates.setCheckout("2019-01-01");

        Booking booking = new Booking();
        booking.setFirstname("Jim");
        booking.setLastname("Brown");
        booking.setAdditionalneeds("Breakfast");
        booking.setBookingdates(bookingdates);
        booking.setTotalprice(111);
        booking.setDepositpaid(true);

        Request response = new Request(booking,1);
        response.setBooking(booking);


        RestAssured
                .given()
                .baseUri("https://restful-booker.herokuapp.com/booking")
                .contentType(ContentType.JSON)
                .body(response)
                .when()
                .post()
                .then()
                .assertThat()
                .statusCode(200);
    }
}
