package AutoGeneratedPOJOs.CreateBook;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Request {

	public Request(Booking booking, int bookingid) {
		this.booking = booking;
		this.bookingid = bookingid;
	}

	@JsonProperty("booking")
	private Booking booking;

	@JsonProperty("bookingid")
	private int bookingid;

	public void setBooking(Booking booking){
		this.booking = booking;
	}

	public Booking getBooking(){
		return booking;
	}

	public void setBookingid(int bookingid){
		this.bookingid = bookingid;
	}

	public int getBookingid(){
		return bookingid;
	}

	@Override
 	public String toString(){
		return 
			"Response{" + 
			"booking = '" + booking + '\'' + 
			",bookingid = '" + bookingid + '\'' + 
			"}";
		}
}